on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch: # Allow manual triggering

name: Build OpenWrt Image

jobs:
  build:
    name: Build BPI-R4 OpenWrt Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build OpenWrt image
        run: nix build .#bpi-r4 --print-build-logs

      - name: List build outputs
        run: ls -la result/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-bpi-r4-images
          path: result/
          retention-days: 30
