name: Update Dependencies

on:
  schedule:
    # Run weekly on Sundays at 1 AM UTC (before nix-config updates)
    - cron: '00 9 * * *' # runs daily at 9:00 (an hour after nix-openwrt-imagebuilder updates)
  workflow_dispatch:
    inputs:
      update-type:
        description: "Type of update to perform"
        required: true
        type: choice
        options:
          - "all"
          - "nixpkgs"
          - "openwrt-imagebuilder"
        default: "all"
      create-pr:
        description: "Create a pull request with the updates"
        required: false
        type: boolean
        default: true

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: nix-community
          skipPush: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update dependencies
        id: update
        run: |
          echo "Updating dependencies..."

          case "${{ github.event.inputs.update-type || 'all' }}" in
            "all")
              echo "Updating all dependencies..."
              nix flake update --accept-flake-config
              ;;
            "nixpkgs")
              echo "Updating nixpkgs..."
              nix flake update --update-input nixpkgs --accept-flake-config
              ;;
            "openwrt-imagebuilder")
              echo "Updating openwrt-imagebuilder..."
              nix flake update --update-input openwrt-imagebuilder --accept-flake-config
              ;;
          esac

          # Check if there are any changes
          if git diff --quiet; then
            echo "No changes to dependencies"
            echo "has-changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Changes detected, committing update..."
          # Add the flake.lock changes
          git add flake.lock
          git commit -m "Update dependencies (${{ github.event.inputs.update-type || 'all' }})"

          # Push the changes
          BRANCH_NAME="update-deps-$(date +%Y%m%d-%H%M%S)"
          git push origin HEAD:$BRANCH_NAME
          echo "has-changes=true" >> $GITHUB_OUTPUT
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: No changes detected
        if: steps.update.outputs.has-changes == 'false'
        run: |
          echo "✅ Dependencies are already up to date - no changes needed"

      - name: Test updated dependencies
        if: steps.update.outputs.has-changes == 'true'
        run: |
          echo "Testing updated dependencies..."
          nix flake check --accept-flake-config
          echo "Testing OpenWrt build..."
          nix build .#bpi-r4 --dry-run --accept-flake-config
          echo "✅ Dependency update validation passed"

      - name: Create Pull Request
        if: ${{ github.event.inputs.create-pr == 'true' && steps.update.outputs.has-changes == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update dependencies (${{ github.event.inputs.update-type || 'all' }})"
          body: |
            This PR updates the flake dependencies.

            **Changes:**
            - Updated dependencies (${{ github.event.inputs.update-type || 'all' }})

            **Testing:**
            - [x] Dependency validation passed
            - [x] OpenWrt build validation passed
            - [ ] Build check workflow passes
          branch: ${{ steps.update.outputs.branch-name }}
          delete-branch: true
